In [1]:
import os

import pandas as pd

In [2]:
def get_all_korean():

    def nextKorLetterFrom(letter):
        lastLetterInt = 15572643
        if not letter:
            return '가'
        a = letter
        b = a.encode('utf8')
        c = int(b.hex(), 16)

        if c == lastLetterInt:
            return False

        d = hex(c + 1)
        e = bytearray.fromhex(d[2:])

        flag = True
        while flag:
            try:
                r = e.decode('utf-8')
                flag = False
            except UnicodeDecodeError:
                c = c+1
                d = hex(c)
                e = bytearray.fromhex(d[2:])
        return e.decode()

    returns = []
    flag = True
    k = ''
    while flag:
        k = nextKorLetterFrom(k)
        if k is False:
            flag = False
        else:
            returns.append(k)
    return returns

In [4]:
def korean2label(letter):
    ch1 = (ord(letter) - ord('가'))//588
    ch2 = ((ord(letter) - ord('가')) - (588*ch1)) // 28
    ch3 = (ord(letter) - ord('가')) - (588*ch1) - 28*ch2
    return ch1,ch2,ch3

In [7]:
ttf_path = "../data/raw/ttf/"
fonts = [f for f in os.listdir(ttf_path) if ".ttf" in f]

In [8]:
fonts

['jeongyeon_4.ttf',
 '나눔손글씨 아름드리 꽃나무.ttf',
 'UhBee Se_hyun Bold.ttf',
 '나눔손글씨 시우 귀여워.ttf',
 'UhBee EUN KYUNG Bold.ttf',
 'dahyun_4.ttf',
 'UhBee U JEONG.ttf',
 'UhBee ann Bold.ttf',
 'UhBee ARyong Bold.ttf',
 '나눔손글씨 버드나무.ttf',
 '나눔손글씨 성실체.ttf',
 '나눔손글씨 몽돌.ttf',
 '나눔손글씨 아빠의 연애편지.ttf',
 '나눔손글씨 여름글씨.ttf',
 'mina_4.ttf',
 '나눔손글씨 아줌마 자유.ttf',
 '나눔손글씨 다행체.ttf',
 'tzuyu_4.ttf',
 '나눔손글씨 가람연꽃.ttf',
 '나눔손글씨 딸에게 엄마가.ttf',
 '나눔손글씨 따뜻한 작별.ttf',
 '나눔손글씨 꽃내음.ttf',
 '나눔손글씨 손편지체.ttf',
 '나눔손글씨 반짝반짝 별.ttf',
 '나눔손글씨 북극성.ttf',
 '나눔손글씨 고딕 아니고 고딩.ttf',
 '나눔손글씨 소방관의 기도.ttf',
 '나눔손글씨 바른정신.ttf',
 'UhBee puding Bold.ttf',
 '나눔손글씨 마고체.ttf',
 '나눔손글씨 곰신체.ttf',
 'momo_6.ttf',
 '나눔손글씨 또박또박.ttf',
 '나눔손

In [49]:
onehot = df[0].apply(korean2onehot)

In [55]:
import sklearn

In [56]:
pca = sklearn.decomposition.PCA

In [57]:
pca

sklearn.decomposition._pca.PCA

In [53]:
!pip3 install -U scikit-learn

In [59]:
onehot.iloc[0]

array([1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [45]:
np.apply_along_axis(korean2onehot, df.values)

TypeError: apply_along_axis() missing 1 required positional argument: 'arr'

In [29]:
import numpy as np
np.eye(19)[11]

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0.,
       0., 0.])

In [23]:
e

bytearray(b'\xea\xb0\x81')

In [ ]:
def get_all_korean():
    
    def nextKorLetterFrom(letter):
        lastLetterInt = 15572643
        if not letter:
            return '가'
        a = letter
        b = a.encode('utf8')
        c = int(b.hex(), 16)

        if c == lastLetterInt:
            return False

        d = hex(c + 1)
        e = bytearray.fromhex(d[2:])

        flag = True
        while flag:
            try:
                r = e.decode('utf-8')
                flag = False
            except UnicodeDecodeError:
                c = c+1
                d = hex(c)
                e = bytearray.fromhex(d[2:])
        return e.decode()
    
    returns = []
    flag = True
    k = ''
    while flag:
        k = nextKorLetterFrom(k)
        if k is False:
            flag = False
        else:
            returns.append(k)
    return returns

In [61]:

bb = torch.zeros([1,256, 16, 16])

In [65]:
bb[:,np.array([1,2,3,4]),:,:] = 1

In [66]:
bb

tensor([[[[0., 0., 0.,  ..., 0., 0., 0.],
          [0., 0., 0.,  ..., 0., 0., 0.],
          [0., 0., 0.,  ..., 0., 0., 0.],
          ...,
          [0., 0., 0.,  ..., 0., 0., 0.],
          [0., 0., 0.,  ..., 0., 0., 0.],
          [0., 0., 0.,  ..., 0., 0., 0.]],

         [[1., 1., 1.,  ..., 1., 1., 1.],
          [1., 1., 1.,  ..., 1., 1., 1.],
          [1., 1., 1.,  ..., 1., 1., 1.],
          ...,
          [1., 1., 1.,  ..., 1., 1., 1.],
          [1., 1., 1.,  ..., 1., 1., 1.],
          [1., 1., 1.,  ..., 1., 1., 1.]],

         [[1., 1., 1.,  ..., 1., 1., 1.],
          [1., 1., 1.,  ..., 1., 1., 1.],
          [1., 1., 1.,  ..., 1., 1., 1.],
          ...,
          [1., 1., 1.,  ..., 1., 1., 1.],
          [1., 1., 1.,  ..., 1., 1., 1.],
          [1., 1., 1.,  ..., 1., 1., 1.]],

         ...,

         [[0., 0., 0.,  ..., 0., 0., 0.],
          [0., 0., 0.,  ..., 0., 0., 0.],
          [0., 0., 0.,  ..., 0., 0., 0.],
          ...,
          [0., 0., 0.,  ..., 0., 0., 